# Generated by Django 3.1.6 on 2021-02-03 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('b_number', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=225, null=True)),
                ('b_writer', models.CharField(blank=True, max_length=225, null=True)),
                ('b_context', models.CharField(blank=True, max_length=10000, null=True)),
                ('b_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'board',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('c_number', models.AutoField(primary_key=True, serialize=False)),
                ('c_context', models.CharField(blank=True, max_length=10000, null=True)),
                ('c_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'comment',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.CharField(max_length=225, primary_key=True, serialize=False)),
                ('pw', models.CharField(blank=True, max_length=225, null=True)),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
    ]
